# 2장 분류(Classification)와 지도학습(Supervised Learning)

## 0. 사이킷런(Scikit-learn)

# 1. 붓꽃 품종 데이터 업로드, 학습, 예측, 평가



In [4]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import accuracy_score

print("사이킷런 버전:", sklearn.__version__)

# 데이터 세트 로딩
iris = load_iris()

# 피쳐 데이터 numpy
iris_data = iris.data

# 레이블값
iris_label = iris.target
print("\n붓꽃 레이블:", iris_label)
print("붓꽃 품종 이름:", iris.target_names)

# DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
print("\n붓꽃 데이터프레임 (상위 3개 행):\n", iris_df.head(3))

# 데이터 분리 (학습 및 테스트 세트)
x_train, x_test, y_train, y_test = train_test_split(
    iris_data, iris_label,
    test_size=0.2,
    random_state=11
)

# Decision Tree 분류기 학습
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train, y_train)

# 예측 수행
pred = dt_clf.predict(x_test)

# 예측 정확도 평가
print("\n예측 정확도: {0:.4f}".format(accuracy_score(y_test, pred)))

사이킷런 버전: 1.6.1

붓꽃 레이블: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
붓꽃 품종 이름: ['setosa' 'versicolor' 'virginica']

붓꽃 데이터프레임 (상위 3개 행):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0  

예측 정확도: 0.9333


## 3. 사이킷런 기반 프레임워크 익히기
### (1) 데이터 분리
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))
     
<class 'sklearn.utils._bunch.Bunch'>

keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)
     
붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

# feature_names
print(f"\nfeature_names type: {type(iris.feature_names).__name__}")
print(f"feature_names length: {len(iris.feature_names)}")
print(iris.feature_names)


In [3]:
# feature_names
print(f"\nfeature_names type: {type(iris.feature_names).__name__}")
print(f"feature_names length: {len(iris.feature_names)}")
print(iris.feature_names)

# target_names
print(f"\ntarget_names type: {type(iris.target_names).__name__}")
print(f"target_names length: {len(iris.target_names)}")
print(iris.target_names)

# data
print(f"\ndata type: {type(iris.data).__name__}")
print(f"data shape: {iris.data.shape}")
print(iris['data'])

# target
print(f"\ntarget type: {type(iris.target).__name__}")
print(f"target shape: {iris.target.shape}")
print(iris.target)

NameError: name 'iris' is not defined

### (2) 교차 검증

In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
import numpy as np

# Iris 데이터 세트 로딩
iris = load_iris()
features = iris.data
label = iris.target

# Decision Tree 분류기 초기화
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드로 K-Fold 객체 생성
kfold = KFold(n_splits=5)

cv_accuracy = []
print("붓꽃 데이터 크기:", features.shape[0])

n_iter = 0
# K-Fold의 split() 호출 시 폴드별 학습/검증 데이터의 인덱스 반환
for train_index, test_index in kfold.split(features):
    # train_index와 test_index를 이용해 학습 데이터와 검증 데이터 분리
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    cv_accuracy.append(accuracy)

# 평균 검증 정확도 계산
print('\n## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))

# cross_val_score를 이용한 간편한 교차 검증
from sklearn.model_selection import cross_val_score

print('\n--- cross_val_score를 이용한 교차 검증 ---')
scores = cross_val_score(dt_clf, features, label, scoring='accuracy', cv=5)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

붓꽃 데이터 크기: 150

#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30

## 평균 검증 정확도: 0.9

--- cross_val_score를 이용한 교차 검증 ---
교차 검증별 정확도: [0.9667 0.9667 0.9    0.9667 1.    ]
평균 검증 정확도: 0.96


## 5. 데이터 전처리
### 1) 데이터 인코딩

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',  '믹서']
# 2차원 ndarray로 변환
items_reshaped = np.array(items).reshape(-1, 1)

# One-Hot Encoding 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items_reshaped)
oh_labels = oh_encoder.transform(items_reshaped)

# 변환 결과는 희소행렬(sparse matrix)이므로, toarray()를 이용해 밀집 행렬(dense matrix)로 변환
print("원-핫 인코딩 데이터:\n", oh_labels.toarray())
print("원-핫 인코딩 데이터 차원:\n", oh_labels.shape)

원-핫 인코딩 데이터:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원:
 (8, 6)


###  pandas를 이용한 One-Hot Encoding 1

In [7]:
import pandas as pd

df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',  '믹서']})
df_onehot = pd.get_dummies(df)
print("pd.get_dummies를 이용한 원-핫 인코딩 데이터:\n", df_onehot)

pd.get_dummies를 이용한 원-핫 인코딩 데이터:
    item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0     True     False    False     False       False     False
1    False      True    False     False       False     False
2    False     False    False     False        True     False
3    False     False    False     False       False      True
4    False     False    False      True       False     False
5    False     False    False      True       False     False
6    False     False     True     False       False     False
7    False     False     True     False       False     False


# 평가
## 1. 정확도

In [8]:
from sklearn.preprocessing import LabelEncoder

# 결측치 처리
def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    return df

# 불필요한 피처 제거
def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    return df

# 레이블 인코딩
def format_features(df):
    # Cabin은 첫 글자만 추출 (예: C123 → C)
    df['Cabin'] = df['Cabin'].str[:1]

    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        df[feature] = le.fit_transform(df[feature])
    return df
def transform_features(df):
    df = fillna(df)          # 결측치 처리
    df = drop_features(df)   # 필요 없는 변수 제거
    df = format_features(df) # 형식 변환 (범주형 → 수치형 등)
    return df

In [9]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

# 불균형 데이터셋에서 정확도의 한계를 보여주기 위한 가짜 분류기
class MyFakeClassifier(BaseEstimator):
  def fit(self, X, y=None):
    pass
  def predict(self, X):
    # 모든 예측을 0으로 반환 (7이 아닌 경우로 예측)
    return np.zeros((len(X), 1), dtype=bool)

# Digit 데이터 로딩 (여기서는 불균형 데이터 설명을 위한 예시)
digits = load_digits()
y = (digits.target == 7).astype(int) # 7이면 1, 아니면 0
x_train, x_test, y_train, y_test = train_test_split(digits.data, y, random_state=11)

# 불균형한 레이블 데이터 분포도 확인 및 가짜 분류기 정확도 출력
print("레이블 테스트 세트 크기:", y_test.shape)
print('테스트 세트 레이블의 0과 1 분포도:')
print(pd.Series(y_test).value_counts())

fakeclf = MyFakeClassifier()
fakeclf.fit(x_train, y_train)
fakepred = fakeclf.predict(x_test)

print('\n모든 예측을 0으로 했을 때 정확도는:{:.3f}'.format(accuracy_score(y_test, fakepred)))

레이블 테스트 세트 크기: (450,)
테스트 세트 레이블의 0과 1 분포도:
0    405
1     45
Name: count, dtype: int64

모든 예측을 0으로 했을 때 정확도는:0.900


In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 타이타닉 데이터 로드
titanic_df = pd.read_csv('Titanic-Dataset.csv')
y_titanic_df = titanic_df['Survived']
x_titanic_df = titanic_df.drop('Survived', axis=1)

# 데이터 전처리
x_titanic_df = transform_features(x_titanic_df)

# 학습/테스트 데이터 분리
x_train, x_test, y_train, y_test = train_test_split(x_titanic_df, y_titanic_df, test_size=0.2, random_state = 0)

# MyDummyClassifier로 예측 및 정확도 확인
myclf = MyDummyClassifier()
myclf.fit(x_train, y_train)
mypredictions = myclf.predict(x_test)
print("정확도 {0:.4f}".format(accuracy_score(y_test, mypredictions)))

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [11]:
from sklearn.metrics import confusion_matrix

# 오차 행렬 출력
confusion_matrix(y_test, mypredictions)

NameError: name 'mypredictions' is not defined

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# 분류 평가 지표를 한 번에 출력하는 함수
def get_clf_eval(y_test, pred):
  confusion = confusion_matrix(y_test, pred)
  accuracy = accuracy_score(y_test, pred)
  precision = precision_score(y_test, pred)
  recall = recall_score(y_test, pred)
  print('오차행렬')
  print(confusion)
  print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}'.format(accuracy, precision, recall))

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 원본 데이터 재로딩 (Logistic Regression 모델을 위해)
titanic_df = pd.read_csv('Titanic-Dataset.csv')
y_titanic_df = titanic_df['Survived']
x_titanic_df = titanic_df.drop('Survived', axis=1)
x_titanic_df = transform_features(x_titanic_df)

# 학습/테스트 데이터 분리
x_train, x_test, y_train, y_test = train_test_split(x_titanic_df, y_titanic_df, test_size=0.2, random_state=11)

# 로지스틱 회귀 모델 학습 및 예측
lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(x_train, y_train)
pred = lr_clf.predict(x_test)

# 평가 지표 출력
get_clf_eval(y_test, pred)

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [14]:
import numpy as np
from sklearn.preprocessing import Binarizer

pred_proba = lr_clf.predict_proba(x_test)
print('pred_proba() 결과 shape: {0}'.format(pred_proba.shape))
print('pred_proba array 앞 3개만 샘플로 추출\n', np.round(pred_proba[:3], 4))

# 예측 확률을 기반으로 이진 분류
pred_proba_result = np.concatenate([np.round(pred_proba, 4), pred.reshape(-1, 1)], axis=1)
print('두 개의 클래스 중에서 더 큰 확률을 클래스 값으로 예측 (확률과 예측값)\n', pred_proba_result[:3])

# 임계값을 변경하며 재현율/정밀도 확인 예시
custom_threshold = 0.5
pred_proba_1 = pred_proba[:,1].reshape(-1,1)
binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)

print(f'\n임계값 {custom_threshold} 적용 시:')
get_clf_eval(y_test, custom_predict)

custom_threshold = 0.4
binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)

print(f'\n임계값 {custom_threshold} 적용 시:')
get_clf_eval(y_test, custom_predict)

NameError: name 'lr_clf' is not defined

In [15]:
# 테스트를 수행할 모든 임곗값을 리스트 객체로 저장.
thresholds = [0.4, 0.45, 0.50, 0.55, 0.60]

def get_eval_by_threshold(y_test, pred_proba_c1, thresholds):
  for custom_threshold in thresholds:
    binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
    custom_predict = binarizer.transform(pred_proba_c1)
    print("\n임계값:", custom_threshold)
    get_clf_eval(y_test, custom_predict)

get_eval_by_threshold(y_test, pred_proba[:,1].reshape(-1,1), thresholds)

NameError: name 'pred_proba' is not defined

In [16]:
from sklearn.metrics import precision_recall_curve
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt

# 레이블 값이 1일 때 예측 확률을 추출
pred_proba_class1 = lr_clf.predict_proba(x_test)[:, 1]

# precision_recall_curve_plot 함수 정의
def precision_recall_curve_plot(y_test, pred_proba_c1):
    # threshold ndarray와 이 threshold에 따른 정밀도, 재현율 ndarray 추출
    precisions, recalls, thresholds = precision_recall_curve(y_test, pred_proba_c1)

    # Plot 그리기
    plt.figure(figsize=(8, 6))
    threshold_boundary = thresholds.shape[0]

    # 정밀도는 점선으로 표시
    plt.plot(thresholds, precisions[0:threshold_boundary], linestyle='--', label='precision')
    plt.plot(thresholds, recalls[0:threshold_boundary], label='recall')

    # threshold 값 X축의 눈금을 0.1 단위로 변경
    start, end = plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1), 2))
    plt.xlabel('Threshold'); plt.ylabel('Precision and Recall')
    plt.legend()
    plt.grid()
    plt.show()

# 곡선 플로팅
precision_recall_curve_plot(y_test, pred_proba_class1)

# 임계값별 정밀도 및 재현율 확인 (사용자 요청 부분)
precision, recalls, thresholds = precision_recall_curve(y_test, pred_proba_class1)
print('반환된 분류 결정 임곗값 배열의 shape:', thresholds.shape)

thr_index = np.arange(0, thresholds.shape[0], 15)
print('샘플 추출을 위한 임계값 배열의 index 10개', thr_index)
print('샘플용 10개의 임곗값:', np.round(thresholds[thr_index], 2))

print('샘플 임계값별 정밀도: ', np.round(precision[thr_index], 3))
print('샘플 임계값별 재현율: ', np.round(recalls[thr_index], 3))

NameError: name 'lr_clf' is not defined

## 2. 오차 행렬

## 3. 정밀도와 재현율

*   **정밀도**: 예측 양성 중 실제 양성 비율로, 거짓 양성을 줄이는 것이 중요합니다.
*   **재현율(민감도)**: 실제 양성 중 양성으로 예측한 비율로, 거짓 음성을 줄이는 것이 중요합니다.

**-> 정밀도와 재현율 모두 높게 유지하는 것이 중요!**

## 4. F1 스코어